#' MDBF (Langform) – Auswertung mit Report-Option
#'
#' @param dat data.frame mit MDBFL1..MDBFL24
#' @param report logical, ob automatischer Report erstellt werden soll
#' @param report_opts benutzerdefinierte Report-Optionen (siehe mdbf_report)
#' @return Liste mit data und einzelnen alpha-Objekten
#' @export
mdbf_scales <- function(dat, report = FALSE, report_opts = NULL) {

  if (!requireNamespace("psych", quietly = TRUE)) {
    stop("Paket 'psych' muss installiert sein")
  }

  # 0) Spaltennamen normalisieren: MDBFL[xx] -> MDBFLxx (Klammern/Spaces/leading zeros weg)
  nm <- names(dat)
  is_bracketed <- grepl("^\\s*MDBFL\\s*\\[\\s*0*(\\d+)\\s*\\]\\s*$", nm, perl = TRUE)
  if (any(is_bracketed)) {
    idx  <- which(is_bracketed)
    nums <- as.integer(sub("^\\s*MDBFL\\s*\\[\\s*0*(\\d+)\\s*\\]\\s*$", "\\1", nm[idx], perl = TRUE))
    nm[idx] <- paste0("MDBFL", nums)
  }
  nm <- trimws(nm)

  # Konflikte abfangen (z. B. MDBFL23 und MDBFL[23] gleichzeitig vorhanden)
  if (any(duplicated(nm))) {
    dups <- unique(nm[duplicated(nm)])
    stop("Konflikt durch Umbenennung: doppelte Spaltennamen: ",
         paste(dups, collapse = ", "),
         ". Bitte die betroffenen Spalten bereinigen.")
  }
  names(dat) <- nm

  # 1) Items prüfen
  required_cols <- paste0("MDBFL", 1:24)
  missing <- setdiff(required_cols, names(dat))
  if (length(missing) > 0) {
    stop("Fehlende Spalten: ", paste(missing, collapse = ", "))
  }

  # 2) Items numerisch machen (Factors sicher über Labels; NAs bei Nicht-Zahlen möglich)
  dat[required_cols] <- lapply(dat[required_cols], function(x) {
    if (is.factor(x)) x <- as.character(x)
    suppressWarnings(as.numeric(x))
  })

  # --- ab hier: dein bisheriger Auswertungscode (psych::alpha, Report etc.) ---
  # ...



  # 2) Umpolung
  dat$MDBFL3_rev  <- 6 - dat$MDBFL3
  dat$MDBFL4_rev  <- 6 - dat$MDBFL4
  dat$MDBFL5_rev  <- 6 - dat$MDBFL5
  dat$MDBFL7_rev  <- 6 - dat$MDBFL7
  dat$MDBFL9_rev  <- 6 - dat$MDBFL9
  dat$MDBFL11_rev <- 6 - dat$MDBFL11
  dat$MDBFL13_rev <- 6 - dat$MDBFL13
  dat$MDBFL16_rev <- 6 - dat$MDBFL16
  dat$MDBFL18_rev <- 6 - dat$MDBFL18
  dat$MDBFL19_rev <- 6 - dat$MDBFL19
  dat$MDBFL22_rev <- 6 - dat$MDBFL22
  dat$MDBFL23_rev <- 6 - dat$MDBFL23

  # 3) Skalendefinitionen
  gs_cols <- c("MDBFL1", "MDBFL8", "MDBFL14", "MDBFL21",
               "MDBFL11_rev", "MDBFL4_rev", "MDBFL16_rev", "MDBFL18_rev")

  wm_cols <- c("MDBFL2", "MDBFL10", "MDBFL20", "MDBFL17",
               "MDBFL5_rev", "MDBFL7_rev", "MDBFL13_rev", "MDBFL23_rev")

  ru_cols <- c("MDBFL6", "MDBFL12", "MDBFL15", "MDBFL24",
               "MDBFL3_rev", "MDBFL9_rev", "MDBFL19_rev", "MDBFL22_rev")

  total_cols <- c(gs_cols, wm_cols, ru_cols)

  # 4) Summenscores
  dat$MDBFL_GS    <- rowSums(dat[gs_cols],    na.rm = TRUE)
  dat$MDBFL_WM    <- rowSums(dat[wm_cols],    na.rm = TRUE)
  dat$MDBFL_RU    <- rowSums(dat[ru_cols],    na.rm = TRUE)
  dat$MDBFL_Total <- rowSums(dat[total_cols], na.rm = TRUE)

  # 5) Alpha-Objekte einzeln berechnen
  alpha_gs <- NULL
  alpha_wm <- NULL
  alpha_ru <- NULL
  alpha_total <- NULL

  # GS Alpha
  try({
    gs_complete <- dat[gs_cols][complete.cases(dat[gs_cols]), ]
    if (nrow(gs_complete) >= 2) {
      alpha_gs <- psych::alpha(gs_complete, warnings = FALSE)
    }
  }, silent = TRUE)

  # WM Alpha
  try({
    wm_complete <- dat[wm_cols][complete.cases(dat[wm_cols]), ]
    if (nrow(wm_complete) >= 2) {
      alpha_wm <- psych::alpha(wm_complete, warnings = FALSE)
    }
  }, silent = TRUE)

  # RU Alpha
  try({
    ru_complete <- dat[ru_cols][complete.cases(dat[ru_cols]), ]
    if (nrow(ru_complete) >= 2) {
      alpha_ru <- psych::alpha(ru_complete, warnings = FALSE)
    }
  }, silent = TRUE)

  # Total Alpha
  try({
    total_complete <- dat[total_cols][complete.cases(dat[total_cols]), ]
    if (nrow(total_complete) >= 2) {
      alpha_total <- psych::alpha(total_complete, warnings = FALSE)
    }
  }, silent = TRUE)

  # 7) Ergebnis vorbereiten
  result <- list(
    data = dat,
    alpha_gs = alpha_gs,
    alpha_wm = alpha_wm,
    alpha_ru = alpha_ru,
    alpha_total = alpha_total,
    scale_cols = list(
      GS = gs_cols,
      WM = wm_cols,
      RU = ru_cols,
      Total = total_cols
    )
  )

  # In Global Environment für Report verfügbar machen
  assign("mdbf_result", result, envir = .GlobalEnv)

  # 8) Report generieren falls gewünscht
  if (report) {
    mdbf_report(result, options = report_opts)
  }

  return(result)
}

#' MDBF HTML Report Generator (robuste Variante mit params)
#'
#' @param mdbf_result Ergebnis von mdbf_scales()
#' @param output_file Pfad für HTML-Datei (optional)
#' @param options Liste an Schaltern: show_alpha_text, show_rel, show_desc, show_box,
#'        show_hist, show_heatmap, show_corr_heatmap, show_corr_heatmap_total
#' @export
mdbf_report <- function(mdbf_result, output_file = "MDBF_Report.html", options = NULL) {
  required_packages <- c("ggplot2", "tidyr", "dplyr", "knitr", "psych", "rmarkdown")
  for (pkg in required_packages) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop("Für Report benötigt: ", paste(required_packages, collapse = ", "))
    }
  }
  # Defaults (alles an)
  defaults <- list(
    show_alpha_text          = TRUE,
    show_rel                 = TRUE,
    show_desc                = TRUE,
    show_box                 = TRUE,
    show_hist                = TRUE,
    show_heatmap             = TRUE,
    show_corr_heatmap        = TRUE,
    show_corr_heatmap_total  = TRUE
  )
  opt <- if (is.null(options)) defaults else utils::modifyList(defaults, options)

  temp_rmd <- tempfile(fileext = ".Rmd")
  rmd_content <- generate_mdbf_rmd()
  writeLines(rmd_content, temp_rmd)

  out_path <- rmarkdown::render(
    temp_rmd,
    output_file = basename(output_file),
    output_dir  = getwd(),
    params = list(mdbf_result = mdbf_result, opt = opt),
    output_format = rmarkdown::html_document(
      toc = TRUE, toc_float = TRUE, theme = "flatly"
    ),
    quiet = TRUE,
    envir = new.env(parent = baseenv())
  )

  cat("MDBF Report erstellt:", normalizePath(out_path), "\n")
  if (interactive()) browseURL(out_path)
  invisible(out_path)
}

#' RMD-Text für MDBF-Report erzeugen (robust, ohne GlobalEnv)
#' Hinweis: arbeitet nur mit params$mdbf_result
generate_mdbf_rmd <- function() {
  c(
    "---",
    "title: 'MDBF Reliabilitäts- und Itemanalyse Report'",
    "output:",
    "  html_document:",
    "    toc: true",
    "    toc_float: true",
    "    theme: flatly",
    "params:",
    "  mdbf_result: NULL",
    "  opt: NULL",
    "---",
    "",
    "```{r setup, include=FALSE}",
    "knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, comment = NA)",
    "library(ggplot2)",
    "library(tidyr)",
    "library(dplyr)",
    "library(knitr)",
    "library(psych)",
    "library(graphics)",
    "library(stats)",
    "```",
    "",
    "<br> <br>",
    "",
    "# Gesamtübersicht",
    "<br>",
    "",
    "```{r overview}",
    "rows <- list()",
    "",
    "safe_num <- function(x) {",
    "  if (is.null(x) || length(x) == 0 || all(is.na(x))) return(NA_real_)",
    "  as.numeric(x)[1]",
    "}",
    "safe_int <- function(x) {",
    "  if (is.null(x) || length(x) == 0 || all(is.na(x))) return(NA_integer_)",
    "  as.integer(x)[1]",
    "}",
    "len_or_na <- function(x) {",
    "  if (is.null(x)) return(NA_integer_)",
    "  safe_int(length(x))",
    "}",
    "",
    "add_row <- function(alpha_obj, scale_label, items_vec) {",
    "  if (is.null(alpha_obj)) return(NULL)",
    "  a_std <- safe_num(alpha_obj$total$std.alpha)",
    "  # Fallback: N = Anzahl vollständiger Zeilen über die Items",
    "  n_obs <- tryCatch(alpha_obj$n.obs, error = function(e) NA_integer_)",
    "  if (is.null(n_obs) || length(n_obs)==0 || is.na(n_obs)) {",
    "    n_obs <- sum(stats::complete.cases(params$mdbf_result$data[, items_vec, drop = FALSE]))",
    "  }",
    "  n_itm <- len_or_na(items_vec)",
    "  data.frame(Skala = scale_label, Alpha = a_std, N = as.integer(n_obs), Items = n_itm,",
    "             stringsAsFactors = FALSE)",
    "}",
    "",
    "rows[[length(rows)+1]] <- add_row(params$mdbf_result$alpha_gs,    'Gute Stimmung (GS)',        params$mdbf_result$scale_cols$GS)",
    "rows[[length(rows)+1]] <- add_row(params$mdbf_result$alpha_wm,    'Wachheit/Müdigkeit (WM)',   params$mdbf_result$scale_cols$WM)",
    "rows[[length(rows)+1]] <- add_row(params$mdbf_result$alpha_ru,    'Ruhe/Unruhe (RU)',          params$mdbf_result$scale_cols$RU)",
    "rows[[length(rows)+1]] <- add_row(params$mdbf_result$alpha_total, 'Gesamtskala',               params$mdbf_result$scale_cols$Total)",
    "",
    "rows <- rows[!vapply(rows, is.null, logical(1))]",
    "if (length(rows) > 0) {",
    "  summary_data <- do.call(rbind, rows)",
    "  knitr::kable(summary_data, caption = 'Gesamtübersicht der Skalenreliabilitäten')",
    "} else {",
    "  cat('Keine Alpha-Werte verfügbar.')",
    "}",
    "```",
    "---",
    "",
    "<br> <br>",
    "",
    "# Gute Stimmung (GS)",
    "",
    "<br>",
    "",
    "```{r alpha_gs, results='asis', eval=isTRUE(params$opt$show_alpha_text)}",
    "alpha_obj  <- params$mdbf_result$alpha_gs",
    "scale_cols <- params$mdbf_result$scale_cols$GS",
    "if (!is.null(alpha_obj)) {",
    "  raw_alpha <- alpha_obj$total$raw_alpha",
    "  std_alpha <- alpha_obj$total$std.alpha",
    "  n_obs     <- tryCatch(alpha_obj$n.obs, error = function(e) NA_integer_)",
    "  if (is.null(n_obs) || length(n_obs)==0 || is.na(n_obs)) {",
    "    n_obs <- sum(stats::complete.cases(params$mdbf_result$data[, scale_cols, drop = FALSE]))",
    "  }",
    "  n_items   <- length(scale_cols)",
    "  ci_result <- try({",
    "    if (!is.na(raw_alpha) && !is.na(n_obs) && n_obs >= 2 && n_items > 1) {",
    "      psych::alpha.ci(alpha = raw_alpha, n.obs = n_obs, n.var = n_items)",
    "    } else stop('CI nicht berechenbar')",
    "  }, silent = TRUE)",
    "",
    "  if (inherits(ci_result, 'try-error')) {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** (N = %d)\\n\\n',",
    "                round(raw_alpha, 2), as.integer(n_obs)))",
    "  } else {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** CI[**%.2f**; **%.2f**] (N = %d)\\n\\n',",
    "                round(raw_alpha, 2),",
    "                round(ci_result$lower.ci, 2),",
    "                round(ci_result$upper.ci, 2),",
    "                as.integer(n_obs)))",
    "  }",
    "} else {",
    "  cat('Alpha nicht verfügbar.\\n\\n')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Reliabilitätsanalyse (Item-Detail)",
    "",
    "```{r rel_gs, eval=isTRUE(params$opt$show_rel)}",
    "alpha_obj  <- params$mdbf_result$alpha_gs",
    "scale_cols <- params$mdbf_result$scale_cols$GS",
    "if (!is.null(alpha_obj) && !is.null(alpha_obj$item.stats)) {",
    "  item_stats <- alpha_obj$item.stats",
    "  alpha_drop <- alpha_obj$alpha.drop",
    "  raw_alpha  <- alpha_obj$total$raw_alpha",
    "  rel_table <- data.frame(",
    "    Item              = rownames(item_stats),",
    "    Trennschärfe      = round(item_stats$r.cor, 2),",
    "    Alpha_if_deleted  = round(alpha_drop$raw_alpha, 3),",
    "    Alpha_gain        = round(alpha_drop$raw_alpha - raw_alpha, 3),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(rel_table, caption = 'Reliabilitätsanalyse – Gute Stimmung (GS)')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Deskriptive Itemstatistiken",
    "",
    "```{r desc_gs, eval=isTRUE(params$opt$show_desc)}",
    "alpha_obj  <- params$mdbf_result$alpha_gs",
    "scale_cols <- params$mdbf_result$scale_cols$GS",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  desc_stats <- psych::describe(scale_data, na.rm = TRUE)",
    "  desc_table <- data.frame(",
    "    Item            = rownames(desc_stats),",
    "    N               = desc_stats$n,",
    "    Mean            = round(desc_stats$mean, 2),",
    "    SD              = round(desc_stats$sd, 2),",
    "    Min             = desc_stats$min,",
    "    Max             = desc_stats$max,",
    "    Skewness        = round(desc_stats$skew, 2),",
    "    Kurtosis        = round(desc_stats$kurtosis, 2),",
    "    Itemschwierigkeit = round(desc_stats$mean / 5, 2),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(desc_table, caption = 'Deskriptive Statistiken – Gute Stimmung (GS)')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Visualisierungen",
    "",
    "<br>",
    "",
    "### Boxplots",
    "",
    "```{r box_gs, fig.width=10, fig.height=6, eval=isTRUE(params$opt$show_box)}",
    "alpha_obj  <- params$mdbf_result$alpha_gs",
    "scale_cols <- params$mdbf_result$scale_cols$GS",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  scale_data_long <- tidyr::pivot_longer(scale_data, cols = tidyr::everything(), names_to = 'Item', values_to = 'Value')",
    "  p <- ggplot2::ggplot(scale_data_long, ggplot2::aes(x = Item, y = Value)) +",
    "    ggplot2::geom_boxplot(fill = 'steelblue', color = 'black', alpha = 0.8) +",
    "    ggplot2::geom_point(position = ggplot2::position_jitter(width = 0.2), alpha = 0.5, size = 1.5) +",
    "    ggplot2::labs(title = 'Boxplots – Gute Stimmung (GS)', x = '', y = 'Wert') +",
    "    ggplot2::scale_y_continuous(breaks = 1:5, limits = c(0.5, 5.5)) +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, face = 'bold', size = 14),",
    "                   axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Histogramme je Item",
    "",
    "<br> ",
    "",
    "```{r hist_gs, fig.width=8, fig.height=5, eval=isTRUE(params$opt$show_hist)}",
    "alpha_obj  <- params$mdbf_result$alpha_gs",
    "scale_cols <- params$mdbf_result$scale_cols$GS",
    "if (!is.null(alpha_obj)) {",
    "  for (it in scale_cols) {",
    "    x <- params$mdbf_result$data[[it]]",
    "    graphics::hist(x, main = paste('Histogram', it), xlab = it,",
    "                   col = 'steelblue', border = 'black',",
    "                   breaks = c(0.5,1.5,2.5,3.5,4.5,5.5),",
    "                   xlim = c(0.5, 5.5), xaxt = 'n',",
    "                   ylim = c(0, max(table(x, useNA = 'no')) * 1.1))",
    "    graphics::axis(side = 1, at = 1:5, labels = 1:5)",
    "  }",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Antwortverteilungen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r heatmap_gs, fig.width=10, fig.height=5, eval=isTRUE(params$opt$show_heatmap)}",
    "if (!is.null(params$mdbf_result$alpha_gs)) {",
    "  sc_names <- params$mdbf_result$scale_cols$GS",
    "  counts <- sapply(sc_names, function(it) table(factor(params$mdbf_result$data[[it]], levels = 1:5)))",
    "  counts <- as.matrix(counts)",
    "  dimnames(counts) <- list(Antwort = as.character(1:5), Item = sc_names)",
    "  df <- as.data.frame(as.table(counts), stringsAsFactors = FALSE)",
    "  names(df) <- c('Antwort','Item','Freq')",
    "  df$Antwort <- factor(df$Antwort, levels = as.character(1:5))",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item, Antwort, fill = Freq)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::geom_text(ggplot2::aes(label = Freq), size = 3) +",
    "    ggplot2::labs(title = 'Antwortverteilung (Heatmap) – GS', x = '', y = 'Kategorie (1–5)') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Inter-Item-Korrelationen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r corr_heatmap_gs, fig.width=8, fig.height=6, eval=isTRUE(params$opt$show_corr_heatmap)}",
    "if (!is.null(params$mdbf_result$alpha_gs)) {",
    "  sc <- params$mdbf_result$data[, params$mdbf_result$scale_cols$GS, drop = FALSE]",
    "  R  <- stats::cor(sc, use = 'pairwise.complete.obs', method = 'spearman')",
    "  df <- as.data.frame(as.table(R), stringsAsFactors = FALSE)",
    "  names(df) <- c('Item1','Item2','Corr')",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item1, Item2, fill = Corr)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::geom_text(ggplot2::aes(label = sprintf('%.2f', Corr)), size = 3) +",
    "    ggplot2::scale_fill_gradient2(limits = c(-1, 1)) +",
    "    ggplot2::coord_equal() +",
    "    ggplot2::labs(title = 'Inter-Item Korrelationen – GS', x = '', y = '') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "# Wachheit/Müdigkeit (WM)",
    "",
    "<br> <br>",
    "",
    "```{r alpha_wm, results='asis', eval=isTRUE(params$opt$show_alpha_text)}",
    "alpha_obj  <- params$mdbf_result$alpha_wm",
    "scale_cols <- params$mdbf_result$scale_cols$WM",
    "if (!is.null(alpha_obj)) {",
    "  raw_alpha <- alpha_obj$total$raw_alpha",
    "  std_alpha <- alpha_obj$total$std.alpha",
    "  n_obs     <- tryCatch(alpha_obj$n.obs, error = function(e) NA_integer_)",
    "  if (is.null(n_obs) || length(n_obs)==0 || is.na(n_obs)) {",
    "    n_obs <- sum(stats::complete.cases(params$mdbf_result$data[, scale_cols, drop = FALSE]))",
    "  }",
    "  n_items   <- length(scale_cols)",
    "  ci_result <- try({",
    "    if (!is.na(raw_alpha) && !is.na(n_obs) && n_obs >= 2 && n_items > 1) {",
    "      psych::alpha.ci(alpha = raw_alpha, n.obs = n_obs, n.var = n_items)",
    "    } else stop('CI nicht berechenbar')",
    "  }, silent = TRUE)",
    "",
    "  if (inherits(ci_result, 'try-error')) {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** (N = %d)\\n\\n',",
    "                round(raw_alpha, 2), as.integer(n_obs)))",
    "  } else {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** CI[**%.2f**; **%.2f**] (N = %d)\\n\\n',",
    "                round(raw_alpha, 2),",
    "                round(ci_result$lower.ci, 2),",
    "                round(ci_result$upper.ci, 2),",
    "                as.integer(n_obs)))",
    "  }",
    "} else {",
    "  cat('Alpha nicht verfügbar.\\n\\n')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Reliabilitätsanalyse (Item-Detail)",
    "",
    "```{r rel_wm, eval=isTRUE(params$opt$show_rel)}",
    "alpha_obj  <- params$mdbf_result$alpha_wm",
    "scale_cols <- params$mdbf_result$scale_cols$WM",
    "if (!is.null(alpha_obj) && !is.null(alpha_obj$item.stats)) {",
    "  item_stats <- alpha_obj$item.stats",
    "  alpha_drop <- alpha_obj$alpha.drop",
    "  raw_alpha  <- alpha_obj$total$raw_alpha",
    "  rel_table <- data.frame(",
    "    Item              = rownames(item_stats),",
    "    Trennschärfe      = round(item_stats$r.cor, 2),",
    "    Alpha_if_deleted  = round(alpha_drop$raw_alpha, 3),",
    "    Alpha_gain        = round(alpha_drop$raw_alpha - raw_alpha, 3),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(rel_table, caption = 'Reliabilitätsanalyse – Wachheit/Müdigkeit (WM)')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Deskriptive Itemstatistiken",
    "",
    "```{r desc_wm, eval=isTRUE(params$opt$show_desc)}",
    "alpha_obj  <- params$mdbf_result$alpha_wm",
    "scale_cols <- params$mdbf_result$scale_cols$WM",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  desc_stats <- psych::describe(scale_data, na.rm = TRUE)",
    "  desc_table <- data.frame(",
    "    Item            = rownames(desc_stats),",
    "    N               = desc_stats$n,",
    "    Mean            = round(desc_stats$mean, 2),",
    "    SD              = round(desc_stats$sd, 2),",
    "    Min             = desc_stats$min,",
    "    Max             = desc_stats$max,",
    "    Skewness        = round(desc_stats$skew, 2),",
    "    Kurtosis        = round(desc_stats$kurtosis, 2),",
    "    Itemschwierigkeit = round(desc_stats$mean / 5, 2),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(desc_table, caption = 'Deskriptive Statistiken – Wachheit/Müdigkeit (WM)')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Visualisierungen",
    "",
    "<br>",
    "",
    "### Boxplots",
    "",
    "```{r box_wm, fig.width=10, fig.height=6, eval=isTRUE(params$opt$show_box)}",
    "alpha_obj  <- params$mdbf_result$alpha_wm",
    "scale_cols <- params$mdbf_result$scale_cols$WM",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  scale_data_long <- tidyr::pivot_longer(scale_data, cols = tidyr::everything(), names_to = 'Item', values_to = 'Value')",
    "  p <- ggplot2::ggplot(scale_data_long, ggplot2::aes(x = Item, y = Value)) +",
    "    ggplot2::geom_boxplot(fill = 'steelblue', color = 'black', alpha = 0.8) +",
    "    ggplot2::geom_point(position = ggplot2::position_jitter(width = 0.2), alpha = 0.5, size = 1.5) +",
    "    ggplot2::labs(title = 'Boxplots – Wachheit/Müdigkeit (WM)', x = '', y = 'Wert') +",
    "    ggplot2::scale_y_continuous(breaks = 1:5, limits = c(0.5, 5.5)) +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, face = 'bold', size = 14),",
    "                   axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Histogramme je Item",
    "",
    "<br> ",
    "",
    "```{r hist_wm, fig.width=8, fig.height=5, eval=isTRUE(params$opt$show_hist)}",
    "alpha_obj  <- params$mdbf_result$alpha_wm",
    "scale_cols <- params$mdbf_result$scale_cols$WM",
    "if (!is.null(alpha_obj)) {",
    "  for (it in scale_cols) {",
    "    x <- params$mdbf_result$data[[it]]",
    "    graphics::hist(x, main = paste('Histogram', it), xlab = it,",
    "                   col = 'steelblue', border = 'black',",
    "                   breaks = c(0.5,1.5,2.5,3.5,4.5,5.5),",
    "                   xlim = c(0.5, 5.5), xaxt = 'n',",
    "                   ylim = c(0, max(table(x, useNA = 'no')) * 1.1))",
    "    graphics::axis(side = 1, at = 1:5, labels = 1:5)",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "<br> <br>",
    "",
    "### Antwortverteilungen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r heatmap_wm, fig.width=10, fig.height=5, eval=isTRUE(params$opt$show_heatmap)}",
    "if (!is.null(params$mdbf_result$alpha_wm)) {",
    "  sc_names <- params$mdbf_result$scale_cols$WM",
    "  counts <- sapply(sc_names, function(it) table(factor(params$mdbf_result$data[[it]], levels = 1:5)))",
    "  counts <- as.matrix(counts)",
    "  dimnames(counts) <- list(Antwort = as.character(1:5), Item = sc_names)",
    "  df <- as.data.frame(as.table(counts), stringsAsFactors = FALSE)",
    "  names(df) <- c('Antwort','Item','Freq')",
    "  df$Antwort <- factor(df$Antwort, levels = as.character(1:5))",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item, Antwort, fill = Freq)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::geom_text(ggplot2::aes(label = Freq), size = 3) +",
    "    ggplot2::labs(title = 'Antwortverteilung (Heatmap) – WM', x = '', y = 'Kategorie (1–5)') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Inter-Item-Korrelationen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r corr_heatmap_wm, fig.width=8, fig.height=6, eval=isTRUE(params$opt$show_corr_heatmap)}",
    "if (!is.null(params$mdbf_result$alpha_wm)) {",
    "  sc <- params$mdbf_result$data[, params$mdbf_result$scale_cols$WM, drop = FALSE]",
    "  R  <- stats::cor(sc, use = 'pairwise.complete.obs', method = 'spearman')",
    "  df <- as.data.frame(as.table(R), stringsAsFactors = FALSE)",
    "  names(df) <- c('Item1','Item2','Corr')",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item1, Item2, fill = Corr)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::geom_text(ggplot2::aes(label = sprintf('%.2f', Corr)), size = 3) +",
    "    ggplot2::scale_fill_gradient2(limits = c(-1, 1)) +",
    "    ggplot2::coord_equal() +",
    "    ggplot2::labs(title = 'Inter-Item Korrelationen – WM', x = '', y = '') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "# Ruhe/Unruhe (RU)",
    "",
    "```{r alpha_ru, results='asis', eval=isTRUE(params$opt$show_alpha_text)}",
    "alpha_obj  <- params$mdbf_result$alpha_ru",
    "scale_cols <- params$mdbf_result$scale_cols$RU",
    "if (!is.null(alpha_obj)) {",
    "  raw_alpha <- alpha_obj$total$raw_alpha",
    "  std_alpha <- alpha_obj$total$std.alpha",
    "  n_obs     <- tryCatch(alpha_obj$n.obs, error = function(e) NA_integer_)",
    "  if (is.null(n_obs) || length(n_obs)==0 || is.na(n_obs)) {",
    "    n_obs <- sum(stats::complete.cases(params$mdbf_result$data[, scale_cols, drop = FALSE]))",
    "  }",
    "  n_items   <- length(scale_cols)",
    "  ci_result <- try({",
    "    if (!is.na(raw_alpha) && !is.na(n_obs) && n_obs >= 2 && n_items > 1) {",
    "      psych::alpha.ci(alpha = raw_alpha, n.obs = n_obs, n.var = n_items)",
    "    } else stop('CI nicht berechenbar')",
    "  }, silent = TRUE)",
    "",
    "  if (inherits(ci_result, 'try-error')) {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** (N = %d)\\n\\n',",
    "                round(raw_alpha, 2), as.integer(n_obs)))",
    "  } else {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** CI[**%.2f**; **%.2f**] (N = %d)\\n\\n',",
    "                round(raw_alpha, 2),",
    "                round(ci_result$lower.ci, 2),",
    "                round(ci_result$upper.ci, 2),",
    "                as.integer(n_obs)))",
    "  }",
    "} else {",
    "  cat('Alpha nicht verfügbar.\\n\\n')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Reliabilitätsanalyse (Item-Detail)",
    "",
    "```{r rel_ru, eval=isTRUE(params$opt$show_rel)}",
    "alpha_obj  <- params$mdbf_result$alpha_ru",
    "scale_cols <- params$mdbf_result$scale_cols$RU",
    "if (!is.null(alpha_obj) && !is.null(alpha_obj$item.stats)) {",
    "  item_stats <- alpha_obj$item.stats",
    "  alpha_drop <- alpha_obj$alpha.drop",
    "  raw_alpha  <- alpha_obj$total$raw_alpha",
    "  rel_table <- data.frame(",
    "    Item              = rownames(item_stats),",
    "    Trennschärfe      = round(item_stats$r.cor, 2),",
    "    Alpha_if_deleted  = round(alpha_drop$raw_alpha, 3),",
    "    Alpha_gain        = round(alpha_drop$raw_alpha - raw_alpha, 3),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(rel_table, caption = 'Reliabilitätsanalyse – Ruhe/Unruhe (RU)')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Deskriptive Itemstatistiken",
    "",
    "```{r desc_ru, eval=isTRUE(params$opt$show_desc)}",
    "alpha_obj  <- params$mdbf_result$alpha_ru",
    "scale_cols <- params$mdbf_result$scale_cols$RU",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  desc_stats <- psych::describe(scale_data, na.rm = TRUE)",
    "  desc_table <- data.frame(",
    "    Item            = rownames(desc_stats),",
    "    N               = desc_stats$n,",
    "    Mean            = round(desc_stats$mean, 2),",
    "    SD              = round(desc_stats$sd, 2),",
    "    Min             = desc_stats$min,",
    "    Max             = desc_stats$max,",
    "    Skewness        = round(desc_stats$skew, 2),",
    "    Kurtosis        = round(desc_stats$kurtosis, 2),",
    "    Itemschwierigkeit = round(desc_stats$mean / 5, 2),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(desc_table, caption = 'Deskriptive Statistiken – Ruhe/Unruhe (RU)')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Visualisierungen",
    "",
    "<br>",
    "",
    "### Boxplots",
    "",
    "```{r box_ru, fig.width=10, fig.height=6, eval=isTRUE(params$opt$show_box)}",
    "alpha_obj  <- params$mdbf_result$alpha_ru",
    "scale_cols <- params$mdbf_result$scale_cols$RU",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  scale_data_long <- tidyr::pivot_longer(scale_data, cols = tidyr::everything(), names_to = 'Item', values_to = 'Value')",
    "  p <- ggplot2::ggplot(scale_data_long, ggplot2::aes(x = Item, y = Value)) +",
    "    ggplot2::geom_boxplot(fill = 'steelblue', color = 'black', alpha = 0.8) +",
    "    ggplot2::geom_point(position = ggplot2::position_jitter(width = 0.2), alpha = 0.5, size = 1.5) +",
    "    ggplot2::labs(title = 'Boxplots – Ruhe/Unruhe (RU)', x = '', y = 'Wert') +",
    "    ggplot2::scale_y_continuous(breaks = 1:5, limits = c(0.5, 5.5)) +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, face = 'bold', size = 14),",
    "                   axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Histogramme je Item",
    "",
    "<br> ",
    "",
    "```{r hist_ru, fig.width=8, fig.height=5, eval=isTRUE(params$opt$show_hist)}",
    "alpha_obj  <- params$mdbf_result$alpha_ru",
    "scale_cols <- params$mdbf_result$scale_cols$RU",
    "if (!is.null(alpha_obj)) {",
    "  for (it in scale_cols) {",
    "    x <- params$mdbf_result$data[[it]]",
    "    graphics::hist(x, main = paste('Histogram', it), xlab = it,",
    "                   col = 'steelblue', border = 'black',",
    "                   breaks = c(0.5,1.5,2.5,3.5,4.5,5.5),",
    "                   xlim = c(0.5, 5.5), xaxt = 'n',",
    "                   ylim = c(0, max(table(x, useNA = 'no')) * 1.1))",
    "    graphics::axis(side = 1, at = 1:5, labels = 1:5)",
    "  }",
    "}",
    "```",
    "",
    "---",
    "",
    "<br> <br>",
    "",
    "### Antwortverteilungen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r heatmap_ru, fig.width=10, fig.height=5, eval=isTRUE(params$opt$show_heatmap)}",
    "if (!is.null(params$mdbf_result$alpha_ru)) {",
    "  sc_names <- params$mdbf_result$scale_cols$RU",
    "  counts <- sapply(sc_names, function(it) table(factor(params$mdbf_result$data[[it]], levels = 1:5)))",
    "  counts <- as.matrix(counts)",
    "  dimnames(counts) <- list(Antwort = as.character(1:5), Item = sc_names)",
    "  df <- as.data.frame(as.table(counts), stringsAsFactors = FALSE)",
    "  names(df) <- c('Antwort','Item','Freq')",
    "  df$Antwort <- factor(df$Antwort, levels = as.character(1:5))",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item, Antwort, fill = Freq)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::geom_text(ggplot2::aes(label = Freq), size = 3) +",
    "    ggplot2::labs(title = 'Antwortverteilung (Heatmap) – RU', x = '', y = 'Kategorie (1–5)') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Inter-Item-Korrelationen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r corr_heatmap_ru, fig.width=8, fig.height=6, eval=isTRUE(params$opt$show_corr_heatmap)}",
    "if (!is.null(params$mdbf_result$alpha_ru)) {",
    "  sc <- params$mdbf_result$data[, params$mdbf_result$scale_cols$RU, drop = FALSE]",
    "  R  <- stats::cor(sc, use = 'pairwise.complete.obs', method = 'spearman')",
    "  df <- as.data.frame(as.table(R), stringsAsFactors = FALSE)",
    "  names(df) <- c('Item1','Item2','Corr')",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item1, Item2, fill = Corr)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::geom_text(ggplot2::aes(label = sprintf('%.2f', Corr)), size = 3) +",
    "    ggplot2::scale_fill_gradient2(limits = c(-1, 1)) +",
    "    ggplot2::coord_equal() +",
    "    ggplot2::labs(title = 'Inter-Item Korrelationen – RU', x = '', y = '') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "# Gesamtskala",
    "",
    "```{r alpha_total, results='asis', eval=isTRUE(params$opt$show_alpha_text)}",
    "alpha_obj  <- params$mdbf_result$alpha_total",
    "scale_cols <- params$mdbf_result$scale_cols$Total",
    "if (!is.null(alpha_obj)) {",
    "  raw_alpha <- alpha_obj$total$raw_alpha",
    "  std_alpha <- alpha_obj$total$std.alpha",
    "  n_obs     <- tryCatch(alpha_obj$n.obs, error = function(e) NA_integer_)",
    "  if (is.null(n_obs) || length(n_obs)==0 || is.na(n_obs)) {",
    "    n_obs <- sum(stats::complete.cases(params$mdbf_result$data[, scale_cols, drop = FALSE]))",
    "  }",
    "  n_items   <- length(scale_cols)",
    "  ci_result <- try({",
    "    if (!is.na(raw_alpha) && !is.na(n_obs) && n_obs >= 2 && n_items > 1) {",
    "      psych::alpha.ci(alpha = raw_alpha, n.obs = n_obs, n.var = n_items)",
    "    } else stop('CI nicht berechenbar')",
    "  }, silent = TRUE)",
    "",
    "  if (inherits(ci_result, 'try-error')) {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** (N = %d)\\n\\n',",
    "                round(raw_alpha, 2), as.integer(n_obs)))",
    "  } else {",
    "    cat(sprintf('Das Raw Cronbachs $\\\\alpha$ beträgt **%.2f** CI[**%.2f**; **%.2f**] (N = %d)\\n\\n',",
    "                round(raw_alpha, 2),",
    "                round(ci_result$lower.ci, 2),",
    "                round(ci_result$upper.ci, 2),",
    "                as.integer(n_obs)))",
    "  }",
    "} else {",
    "  cat('Alpha nicht verfügbar.\\n\\n')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Reliabilitätsanalyse (Item-Detail)",
    "",
    "```{r rel_total, eval=isTRUE(params$opt$show_rel)}",
    "alpha_obj  <- params$mdbf_result$alpha_total",
    "scale_cols <- params$mdbf_result$scale_cols$Total",
    "if (!is.null(alpha_obj) && !is.null(alpha_obj$item.stats)) {",
    "  item_stats <- alpha_obj$item.stats",
    "  alpha_drop <- alpha_obj$alpha.drop",
    "  raw_alpha  <- alpha_obj$total$raw_alpha",
    "  rel_table <- data.frame(",
    "    Item              = rownames(item_stats),",
    "    Trennschärfe      = round(item_stats$r.cor, 2),",
    "    Alpha_if_deleted  = round(alpha_drop$raw_alpha, 3),",
    "    Alpha_gain        = round(alpha_drop$raw_alpha - raw_alpha, 3),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(rel_table, caption = 'Reliabilitätsanalyse – Gesamtskala')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Deskriptive Itemstatistiken",
    "",
    "```{r desc_total, eval=isTRUE(params$opt$show_desc)}",
    "alpha_obj  <- params$mdbf_result$alpha_total",
    "scale_cols <- params$mdbf_result$scale_cols$Total",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  desc_stats <- psych::describe(scale_data, na.rm = TRUE)",
    "  desc_table <- data.frame(",
    "    Item            = rownames(desc_stats),",
    "    N               = desc_stats$n,",
    "    Mean            = round(desc_stats$mean, 2),",
    "    SD              = round(desc_stats$sd, 2),",
    "    Min             = desc_stats$min,",
    "    Max             = desc_stats$max,",
    "    Skewness        = round(desc_stats$skew, 2),",
    "    Kurtosis        = round(desc_stats$kurtosis, 2),",
    "    Itemschwierigkeit = round(desc_stats$mean / 5, 2),",
    "    stringsAsFactors = FALSE",
    "  )",
    "  knitr::kable(desc_table, caption = 'Deskriptive Statistiken – Gesamtskala')",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "## Visualisierungen",
    "",
    "<br>",
    "",
    "### Boxplots",
    "",
    "```{r box_total, fig.width=10, fig.height=6, eval=isTRUE(params$opt$show_box)}",
    "alpha_obj  <- params$mdbf_result$alpha_total",
    "scale_cols <- params$mdbf_result$scale_cols$Total",
    "if (!is.null(alpha_obj)) {",
    "  scale_data <- params$mdbf_result$data[, scale_cols, drop = FALSE]",
    "  scale_data_long <- tidyr::pivot_longer(scale_data, cols = tidyr::everything(), names_to = 'Item', values_to = 'Value')",
    "  p <- ggplot2::ggplot(scale_data_long, ggplot2::aes(x = Item, y = Value)) +",
    "    ggplot2::geom_boxplot(fill = 'steelblue', color = 'black', alpha = 0.8) +",
    "    ggplot2::geom_point(position = ggplot2::position_jitter(width = 0.2), alpha = 0.5, size = 1.5) +",
    "    ggplot2::labs(title = 'Boxplots – Gesamtskala', x = '', y = 'Wert') +",
    "    ggplot2::scale_y_continuous(breaks = 1:5, limits = c(0.5, 5.5)) +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, face = 'bold', size = 14),",
    "                   axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Histogramme je Item",
    "",
    "<br> ",
    "",
    "```{r hist_total, fig.width=8, fig.height=5, eval=isTRUE(params$opt$show_hist)}",
    "alpha_obj  <- params$mdbf_result$alpha_total",
    "scale_cols <- params$mdbf_result$scale_cols$Total",
    "if (!is.null(alpha_obj)) {",
    "  for (it in scale_cols) {",
    "    x <- params$mdbf_result$data[[it]]",
    "    graphics::hist(x, main = paste('Histogram', it), xlab = it,",
    "                   col = 'steelblue', border = 'black',",
    "                   breaks = c(0.5,1.5,2.5,3.5,4.5,5.5),",
    "                   xlim = c(0.5, 5.5), xaxt = 'n',",
    "                   ylim = c(0, max(table(x, useNA = 'no')) * 1.1))",
    "    graphics::axis(side = 1, at = 1:5, labels = 1:5)",
    "  }",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Antwortverteilungen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r heatmap_total, fig.width=16, fig.height=5, eval=isTRUE(params$opt$show_heatmap)}",
    "if (!is.null(params$mdbf_result$alpha_total)) {",
    "  sc_names <- params$mdbf_result$scale_cols$Total",
    "  counts <- sapply(sc_names, function(it) table(factor(params$mdbf_result$data[[it]], levels = 1:5)))",
    "  counts <- as.matrix(counts)",
    "  dimnames(counts) <- list(Antwort = as.character(1:5), Item = sc_names)",
    "  df <- as.data.frame(as.table(counts), stringsAsFactors = FALSE)",
    "  names(df) <- c('Antwort','Item','Freq')",
    "  df$Antwort <- factor(df$Antwort, levels = as.character(1:5))",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item, Antwort, fill = Freq)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::geom_text(ggplot2::aes(label = Freq), size = 3) +",
    "    ggplot2::labs(title = 'Antwortverteilung (Heatmap) – Gesamtskala', x = '', y = 'Kategorie (1–5)') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))",
    "  print(p)",
    "}",
    "```",
    "",
    "<br> <br>",
    "",
    "### Inter-Item-Korrelationen (Heatmap)",
    "",
    "<br>",
    "",
    "```{r corr_heatmap_total, fig.width=16, fig.height=10, eval=isTRUE(params$opt$show_corr_heatmap_total)}",
    "if (!is.null(params$mdbf_result$alpha_total)) {",
    "  # Reihenfolge: GS, WM, RU",
    "  gs <- params$mdbf_result$scale_cols$GS",
    "  wm <- params$mdbf_result$scale_cols$WM",
    "  ru <- params$mdbf_result$scale_cols$RU",
    "  sc_order <- c(gs, wm, ru)",
    "",
    "  sc <- params$mdbf_result$data[, sc_order, drop = FALSE]",
    "  R  <- stats::cor(sc, use = 'pairwise.complete.obs', method = 'spearman')",
    "",
    "  df <- as.data.frame(as.table(R), stringsAsFactors = FALSE)",
    "  names(df) <- c('Item1','Item2','Corr')",
    "  df$Item1 <- factor(df$Item1, levels = sc_order)",
    "  df$Item2 <- factor(df$Item2, levels = sc_order)",
    "",
    "  # gestrichelte Trennlinien zwischen den Subskalen",
    "  n_gs <- length(gs); n_wm <- length(wm); n_ru <- length(ru)",
    "  cuts <- c(n_gs + 0.5, n_gs + n_wm + 0.5)",
    "",
    "  p <- ggplot2::ggplot(df, ggplot2::aes(Item1, Item2, fill = Corr)) +",
    "    ggplot2::geom_tile() +",
    "    ggplot2::scale_fill_gradient2(limits = c(-1, 1)) +",
    "    ggplot2::coord_equal() +",
    "    ggplot2::labs(title = 'Inter-Item Korrelationen – Gesamtskala (GS | WM | RU)', x = '', y = '') +",
    "    ggplot2::theme_minimal() +",
    "    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust = 1)) +",
    "    ggplot2::geom_vline(xintercept = cuts, linetype = 'dashed', linewidth = 0.3) +",
    "    ggplot2::geom_hline(yintercept = cuts, linetype = 'dashed', linewidth = 0.3)",
    "",
    "  # Zahlen nur einblenden, wenn es nicht zu eng wird",
    "  if (length(sc_order) <= 18) {",
    "    p <- p + ggplot2::geom_text(ggplot2::aes(label = sprintf('%.2f', Corr)), size = 3)",
    "  }",
    "  print(p)",
    "}",
    "```",
    "",
    ""
  )
}

#' Schnelle Alpha-Übersicht
#'
#' @param mdbf_result Ergebnis von mdbf_scales()
#' @export
show_mdbf_alphas <- function(mdbf_result) {
  cat("MDBF Cronbachs Alpha Übersicht:\n")
  cat("===============================\n")

  scales <- c("gs", "wm", "ru", "total")
  scale_names <- c("Gute Stimmung (GS)", "Wachheit/Müdigkeit (WM)",
                   "Ruhe/Unruhe (RU)", "Gesamtskala")

  for (i in seq_along(scales)) {
    alpha_obj <- mdbf_result[[paste0("alpha_", scales[i])]]
    if (!is.null(alpha_obj)) {
      cat(scale_names[i], ": α =", round(alpha_obj$total$std.alpha, 3),
          "(N =", alpha_obj$n.obs, ")\n")
    } else {
      cat(scale_names[i], ": Berechnung fehlgeschlagen\n")
    }
  }
}
